name: Release new version

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Semantic level bump'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "Miles Bot"
          git config user.email noreply@3zbrands.com

      - name: Bump version
        id: bump-version
        run: echo "version=$(npm version ${{ inputs.level }} --tag-version-prefix=)" >> $GITHUB_OUTPUT

      - name: Commit changes
        run: git commit -m "Bump version to ${{ steps.bump-version.outputs.version }}"

      - name: Push new branch
        run: git push origin main

      - name: Create new release
        run: gh release create ${{ steps.bump-version.outputs.version }} --generate-notes --latest
        env:
          GITHUB_TOKEN: ${{ secrets.MILES_BOT_TOKEN }}
